<?xml version="1.0" encoding="utf-8"?><Database Name="Library" Class="ClientDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Library.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.registration" Member="registrations">
    <Type Name="registration">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="mobile" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>